mysql:
    build: ./mysql
    container_name: mysql_server
#    volumes:
#       - /var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: fl4rumR0cks
        MYSQL_USER: flarum
        MYSQL_PASSWORD: flarum
        MYSQL_DATABASE: flarum
weba:
    build: ./php
    container_name: flarum_server
    links:
        - mysql
    expose:
        - 80
    ports:
        - 80:80
